// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-HYAFKKm1Mn3skB7_SuddkbfS0CFeLYI',
    appId: '1:838886503379:web:5eae9db573b80cc9237526',
    messagingSenderId: '838886503379',
    projectId: 'ondaurbanita-radio',
    authDomain: 'ondaurbanita-radio.firebaseapp.com',
    storageBucket: 'ondaurbanita-radio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BI6JKwpvaRkdMzbqEEDfh-kR33sZglw',
    appId: '1:838886503379:android:0ffc87a8cfbad744237526',
    messagingSenderId: '838886503379',
    projectId: 'ondaurbanita-radio',
    storageBucket: 'ondaurbanita-radio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6K2E5tdiUhzCNS3Dyh5RqNf4BV_jJAzg',
    appId: '1:838886503379:ios:a507855ff6eb35ba237526',
    messagingSenderId: '838886503379',
    projectId: 'ondaurbanita-radio',
    storageBucket: 'ondaurbanita-radio.firebasestorage.app',
    iosBundleId: 'com.example.proyectoOndaurbanita',
  );
}
